version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "6321:80"
    volumes:
      - ./local/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html
    depends_on:
      - fibo-be-php
    links:
      - fibo-be-php


  fibo-be-php:
    build:
      context: .
      target: local
    container_name: fibo-be-php
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./local/xdebug:/usr/local/etc/php/conf.d/
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./vendor:/var/www/vendor
      - ./tests:/var/www/tests
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock


